version: "3.9"

services:
  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
